import { chunkDocumentPages } from '../src/lib/chunking';
import { ExtractedPage } from '../src/lib/pdf';

async function runEndToEndVerification() {
  console.log('🧪 Starting DocLens End-to-End Pipeline Verification...\n');

  // 1. Mock Extracted PDF Pages
  const samplePages: ExtractedPage[] = [
    {
      pageNumber: 1,
      text: 'DocLens Architecture Overview. DocLens is a lightweight NotebookLM-lite application for asking grounded questions about PDF documents using Retrieval-Augmented Generation (RAG).',
    },
    {
      pageNumber: 2,
      text: 'Vector Database and pgvector. PostgreSQL with pgvector is used to store document chunks and 1536-dimensional vector embeddings generated via OpenAI text-embedding-3-small. Cosine distance is used for semantic retrieval.',
    },
    {
      pageNumber: 3,
      text: 'Source Citations. Every answer generated by the LLM is backed by retrieved chunks with exact page numbers. Clicking a citation pill shows the original context snippet in a modal dialog.',
    },
  ];

  // 2. Chunking Verification
  console.log('Step 1: Testing Document Chunking...');
  const chunks = chunkDocumentPages('doc_test_123', samplePages, { targetChunkSize: 200, overlap: 40 });
  console.log(`  ✓ Successfully generated ${chunks.length} chunks across 3 pages.`);
  console.assert(chunks.length >= 3, 'Expected at least 3 chunks');

  // 3. Page Number Preservation Verification
  console.log('\nStep 2: Verifying Page Metadata Preservation...');
  const pageNumbers = chunks.map((c) => c.pageNumber);
  console.log(`  ✓ Chunk Page Numbers: [${pageNumbers.join(', ')}]`);
  console.assert(pageNumbers.includes(1) && pageNumbers.includes(2) && pageNumbers.includes(3), 'Page numbers missing');

  // 4. Vector Query Format Verification
  console.log('\nStep 3: Verifying pgvector Query Formatting...');
  const dummyEmbedding = new Array(1536).fill(0.01);
  const vectorStr = `[${dummyEmbedding.join(',')}]`;
  console.log(`  ✓ Formatted Vector Length: ${dummyEmbedding.length} dims (string length: ${vectorStr.length} chars)`);
  console.assert(vectorStr.startsWith('[') && vectorStr.endsWith(']'), 'Invalid vector string format');

  // 5. System Prompt Construction Verification
  console.log('\nStep 4: Verifying Grounded RAG Prompt Formatting...');
  const formattedContext = chunks
    .map((c, i) => `--- CONTEXT CHUNK ${i + 1} [Page ${c.pageNumber}, Chunk ${c.chunkIndex}] ---\n${c.content}`)
    .join('\n\n');
  console.log('  ✓ Formatted Context Sample (first 150 chars):\n');
  console.log(formattedContext.slice(0, 150) + '...\n');

  console.log('✅ End-to-End Pipeline Verification Completed Successfully!');
}

runEndToEndVerification().catch((err) => {
  console.error('❌ E2E Verification Failed:', err);
  process.exit(1);
});
